# cloudbuild-native.yaml: Build nativo e deploy no Cloud Run Functions (mais compatível com containers)

# Substituições necessárias (defina na execução do build)
# _REGION=southamerica-east1
# _REPOSITORY=cloud-run-source-teste-pubsub
# _SERVICE_NAME=serveless-test-pubsub

# NOTA: Usando Cloud Run Functions em vez de Cloud Functions Gen 2 para melhor suporte a containers

steps:
  # 1. Criar repositório Artifact Registry se não existir
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create Artifact Registry'
    entrypoint: 'gcloud'
    args:
      - 'artifacts'
      - 'repositories'
      - 'create'
      - '${_REPOSITORY}'
      - '--repository-format=docker'
      - '--location=${_REGION}'
      - '--project=${PROJECT_ID}'
    allow_failure: true  # Permite falha se o repositório já existir

  # 2. Implanta a função de evaluation
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy pubsub evaluation Function'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'evaluation-function'
      - '--source=.'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--platform=managed'
      - '--port=8080'

# O Cloud Build fará o build e deploy automático dos Cloud Run services quando usar --source com Dockerfile.

# Aumenta o timeout padrão, pois a compilação nativa pode demorar
timeout: '1800s' # 30 minutos

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'
