# cloudbuild.yaml
# Pipeline: Run DB migrations (Flyway) -> Build & push container -> Deploy Cloud Function (gen2)

substitutions:
  _SERVICE_NAME: "evaluation-function"
  _REGION: "southamerica-east1"
  _IMAGE: "gcr.io/$PROJECT_ID/evaluation-function"

# Make secrets available as environment variables via Secret Manager
availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/db-postgresql-application-password/versions/latest"
      env: "DB_PASS"
    - versionName: "projects/$PROJECT_ID/secrets/DB_USER_POSTECH-FIAP-TCF4/versions/latest"
      env: "DB_USER"
    - versionName: "projects/$PROJECT_ID/secrets/DB_URL_POSTECH-FIAP-TCF4/versions/latest"
      env: "DB_URL"
    # Secret used by your Cloud Run service manifest
    - versionName: "projects/$PROJECT_ID/secrets/db-postgresql-application-password/versions/latest"
      env: "DB_PASSWORD"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Run Flyway migrations using the SQL files in the repo
  - name: 'gcr.io/flyway/flyway'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        echo "Running Flyway migrations..."
        flyway -url="$DB_URL" -user="$DB_USER" -password="$DB_PASS" -locations=filesystem:src/main/resources/db/migration migrate
    env:
      - 'DB_URL=$DB_URL'
      - 'DB_USER=$DB_USER'
      - 'DB_PASS=$DB_PASS'

  # 2) Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}:$SHORT_SHA', '.']

  # 3) Push container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:$SHORT_SHA']

  # 4) Deploy to Cloud Run (managed) — adjusted for existing Cloud Run setup
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-lc'
      - |
        echo "Deploying Cloud Run service ${_SERVICE_NAME} to ${_REGION}..."
        gcloud run deploy ${_SERVICE_NAME} --region=${_REGION} --image=${_IMAGE}:$SHORT_SHA --platform=managed --quiet
        echo "(Optional) Bind Secret Manager secret to the service runtime if not set already:"
        echo "gcloud run services update ${_SERVICE_NAME} --region=${_REGION} --update-secrets DB_PASSWORD=projects/$PROJECT_ID/secrets/db-postgresql-application-password:latest"
        echo "You can add DB_USER/DB_URL similarly if you stored them as secrets."

images:
  - '${_IMAGE}:$SHORT_SHA'

# Notes:
# - Create secrets in Secret Manager: DB_URL, DB_USER, DB_PASS
#   Example: gcloud secrets create DB_PASS --data-file=- <<<"mypassword"
# - Adjust `--entry-point` and trigger flags according to your function (HTTP, Pub/Sub, etc.)
# - Optionally, add approvals/backups before running migrations in production
