# Cloud Build config for repository
# - Builds and pushes Docker image
# - Sets logging so triggers using a serviceAccount are accepted

options:
  logging: CLOUD_LOGGING_ONLY
  # Aumenta recursos para build nativo do Quarkus
  machineType: 'E2_HIGHCPU_8'  # 8 vCPUs, 7.2 GB RAM
  diskSizeGb: 100  # Aumenta espaço em disco para build nativo

substitutions:
  _IMAGE: "gcr.io/${_PROJECT_ID}/evaluation-function"

steps:
  # Build Docker image (native binary Dockerfile already in repo)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_IMAGE}:$SHORT_SHA'
      - '-t'
      - '${_IMAGE}:latest'
      - '.'

  # Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:$SHORT_SHA']

  # Push latest tag também
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:latest']

images:
  - '${_IMAGE}:$SHORT_SHA'
  - '${_IMAGE}:latest'

# Optional: deploy to Cloud Run (uncomment and adjust region/service if needed) teste
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       gcloud run deploy evaluation-function \
#         --image ${_IMAGE}:$SHORT_SHA \
#         --region southamerica-east1 \
#         --platform managed \
#         --quiet
