# Cloud Build config for repository
# - Builds and pushes Docker image
# - Sets logging so triggers using a serviceAccount are accepted

options:
  logging: CLOUD_LOGGING_ONLY
  # Aumenta recursos para build nativo do Quarkus
  machineType: 'E2_HIGHCPU_8'  # 8 vCPUs, 7.2 GB RAM
  diskSizeGb: 100  # Aumenta espaço em disco para build nativo

steps:
  # Build Docker image (native binary Dockerfile already in repo)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/evaluation-function:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/evaluation-function:latest'
      - '.'

  # Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/evaluation-function:$SHORT_SHA']

  # Push latest tag também
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/evaluation-function:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy evaluation-function \
          --image gcr.io/$PROJECT_ID/evaluation-function:$SHORT_SHA \
          --region southamerica-east1 \
          --platform managed \
          --port 8080 \
          --allow-unauthenticated \
          --quiet

images:
  - 'gcr.io/$PROJECT_ID/evaluation-function:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/evaluation-function:latest'


